name: internationalization_application
description: "A Flutter application that demonstrates internationalization."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
  package_rename: ^1.7.1

flutter:
  generate: true # useful to generate locales
  uses-material-design: true

# execute in the terminal 'dart run icons_launcher:create' to generate icons
icons_launcher:
  image_path: assets/logo.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    windows:
      enable: true
    macos:
      enable: true
    linux:
      enable: true

# execute in the terminal 'dart run package_rename' to change packages informations
package_rename_config:
  android:
    app_name: Internationalization Example App # (String) The display name of the android app
    package_name: it.ilcondora.internationalizationexampleapp # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: kotlin # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: Internationalization Example App # (String) The display name of the ios app
    bundle_name: internationalizationexampleapp # (String) The bundle name of the ios app
    package_name: it.ilcondora.internationalizationexampleapp # (String) The product bundle identifier of the ios app

  web:
    app_name: Internationalization Example App # (String) The title of the web app and PWA
    short_app_name: # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: An example app that demonstrates internationalization. # (String) The description of the web app and PWA

  windows:
    app_name: Internationalization Example App # (String) The window title & software name of the windows app
    organization: ilCONDORA # (String) The organization name (company name) of the windows app
    copyright_notice: Copyright ©️ 2024 ilCONDORA. All rights reserved. # (String) The legal copyright of the windows app
    exe_name: iea-win64 # (String) The executable name (binary name) of the windows app

  macos:
    app_name: Internationalization Example App # (String) The product name of the macos app
    package_name: it.ilcondora.internationalizationexampleapp # (String) The product bundle identifier of the macos app
    copyright_notice: Copyright ©️ 2024 ilCONDORA. All rights reserved. # (String) The product copyright of the macos app

  linux:
    app_name: Internationalization Example App # (String) The window title of the linux app
    package_name: it.ilcondora.internationalizationexampleapp # (String) The application id of the linux app
    exe_name: iea-linux-x64 # (String) The executable name (binary name) of the linux app

